---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define upgrade_packages.
  set_fact:
    upgrade_packages: "{{ __upgrade_packages }}"
  when: upgrade_packages is not defined
